blank_issues_enabled: false
contact_links:
  - name: ğŸ› Bugs
    url: https://github.com/iorate/ublacklist/discussions/new?category=bugs
    about: "Raise a bug report"
  - name: ğŸ’¬ General
    url: https://github.com/iorate/ublacklist/discussions/new?category=general
    about: "Anything that doesn't fit into other categories"
  - name: ğŸ’¡ Ideas
    url: https://github.com/iorate/ublacklist/discussions/new?category=ideas
    about: "Suggest your feature idea"
  - name: â“ Q&A
    url: https://github.com/iorate/ublacklist/discussions/new?category=q-a
    about: "Ask about usage, configuration, or troubleshooting"
