name: Crowdin

on:
  push:
    branches:
      - master
    paths:
      - src/_locales/en/messages.json
      - README.md
  workflow_dispatch: {}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.PULL_REQUEST_TOKEN }}

      - name: Crowdin
        uses: crowdin/github-action@b4b468cffefb50bdd99dd83e5d2eaeb63c880380 # v2.14.0
        with:
          download_translations: true
          export_only_approved: true
          download_translations_args: --ignore-match
          pull_request_base_branch_name: master
        env:
          GITHUB_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
